### ISSUE TITLE
On the job

### ISSUE THREAD

**Issue by iam-peekay** [AimeeKnight/ama#1]
What is your day to day like as a junior software engineer? Senior software engineer?

**Comment by iam-peekay** [comment]
Why did you choose to go the bootcamp route vs. learning on your own?

**Comment by iam-peekay** [comment]
What is the toughest part about being a software engineer for you? (e.g. time commitment, mostly male, etc.)

**Comment by iam-peekay** [comment]
Now that you're a software engineer, what do you aspire to do from here?

**Comment by iam-peekay** [comment]
What are (if any) issues you face being a women in the field?

**Comment by AimeeKnight** [comment]
What is your day to day like as a junior software engineer? Senior software engineer?

At SparkPost, where I work, the day to day for a junior and senior actually look pretty similar. We all pull stories/tickets from the same bucket. The amount of time I spent off hours learning is where I think the difference is lies. 

With that said, I'm usually at work from 9:30AM to 6:30PM. (On Tuesday's and Friday's I work from home.) We have a 15 minute standup in the morning, then I spend the rest of the day working on various tickets that have been prioritized during our weekly grooming (where we determine the size of the stories that need to be worked on, and gather broad details related to the task.)

As far as my time away from work, I usually wake up between 5AM and 6AM (I'm a morning person due to spending so many early mornings training on the ice). I head to the gym and then for a 4 mile run. I included this in my "day to day", because I actually think it's a really important part of being an engineer. We don't get much physical activity, so I like to make sure I'm taking care of myself. After work I'm either catching up on some more things for work, or working towards learning something else! I also make sure I'm working on learning something new for at least 4-6 hours on Saturday and Sunday.

**Comment by AimeeKnight** [comment]
Why did you choose to go the bootcamp route vs. learning on your own?

I chose to attend a bootcamp because I wanted to accelerate the rate at which I learned things.  You can definitely learn on your own, but going to a boot camp will speed up the process.  Basically, you're trading time for money. I do think it's important to note, that most bootcamps are designed to take you from 20% of the way to 80%. The more you can prep before, the more you'll get out of the time you're there. For me, I also spent off hours my first year (and still do) on the job, learning additional things on my own.

**Comment by AimeeKnight** [comment]
What is the toughest part about being a software engineer for you? (e.g. time commitment, mostly male, etc.)

For me, it's finding a good balance. I definitely struggle with putting too may things on my plate trying to keep up with the latest things coming out, while also making up for lost time learning general principles since I've only been doing this a little over two years! I absolutely love it, but my family has to frequently remind me to slow down and keep my priorities in life straight!

**Comment by AimeeKnight** [comment]
What are (if any) issues you face being a women in the field?

I've definitely showed up to a few events from time to time and could tell some of the guys weren't use to see a female there! Lol! Most of the time it's just funny looks when they find out you're not a recruiter or a girl friend. Honestly, that doesn't bother me too much. They only thing that kinda stinks, is when guys act a little gross. Either burping and such, or making random sexual jokes amongst themselves. I think it's just important to let people know that something is inappropriate as soon as it happens. You don't have to be snappy or anything, just get your point across calmly and firmly. Most of the time, guys don't even realize :smile:

**Comment by AimeeKnight** [comment]
Now that you're a software engineer, what do you aspire to do from here?

My first goal was to reach a point where my problem solving abilities, and technical familiarity resemble a mid level dev. I'm definitely reaching that on the front end, but am now focusing much more on the back end. At the end of the day, I think it's less about back end vs front end, and more about your experiences, and problem solving abilities. 

I've also made it a goal to start speaking at more conferences. Giving both soft skill, and technical talks. For me, that translates into a long term goal I have, which is to take a position as a developer evangelist somewhere.
