### ISSUE TITLE
Problem Solving

### ISSUE THREAD

**Issue by CarlMungazi** [AimeeKnight/ama#11]
Hey Aimee,

What does your problem solving process look like? I've been learning how to code for the past year and only now am I beginning to realise that coding is more about using different tools and languages to solve problems as opposed to being an expert in a particular field. 

Good interview on JavaScript Jabber btw!

**Comment by AimeeKnight** [comment]
@CarlMungazi this is a great question. There are a couple things I'm doing to grow in this area. First, I've intentionally chosen to spend time outside of work working through the problems on Interview Cake (and other similar sites), rather than using that time to dig deeper into say React, and Angular 2. I came to similar realizations as you mentioned during my first year as a junior, and felt improving my problem solving skills was a higher priority for the 3rd and 4th quarter of my first year at work. In addition to that, I've also intentionally spent some time studying data structures, algorithms, design patterns, JS at a deeper level, and finally just understanding how computers work at a bit of a lower level. While bootcamps and self teaching are great practically, I think the time I've spent studying the other areas helps me to think through the code I write much, much, much better. Hope that helps! I've added links to some resources below.
- https://github.com/mgechev/javascript-algorithms
- https://github.com/getify/You-Dont-Know-JS
- https://www.interviewcake.com/
- https://www.youtube.com/user/UNSWelearning/playlists?shelf_id=6&view=50&sort=dd
