### ISSUE TITLE
Your strategy for switching focus

### ISSUE THREAD

**Issue by treble37** [AimeeKnight/ama#12]
Hi Aimee,

In a recent podcast pick, you mentioned you switched focus from the front end to the back end and how important you thought it was not to jump around too much when learning something new.  You said you spent 1 year learning Angular before you decided to move to the backend.  I'm curious about your goal setting strategy - did you make it time-based (e.g., "1 year learning Angular") or milestone-based (e.g., I will learn X, Y, and Z about Angular and then switch to learning about node backend)?  Also, why cutoff the front end after 1 year?  You could have spent time learning about more front end topics such as HTML/CSS, more Angular, React, Elm, etc.  Mostly just curious about your framework for decision making.  I thought your pick was very interesting (and relevant to myself as well), as I'm quite interested in goal setting as well.

Thank you,
Bruce

**Comment by AimeeKnight** [comment]
Hi @treble37! You're totally correct! There is definitely a lot more to learn on the front end! That's one reason I think my personality was drawn to this field. There is a never ending supply of things to learn and get better at! 

With that said, I decided to switch to the back end when I reached a point at work where I didn't have to rely on the seniors like I did when I was really new. I do full stack JavaScript at work, and I noticed that I could pretty easily make my way through tickets on the front end, even help more advanced developers in areas, but I had a lot of questions about our back end and infrastructure. I like to think of it as peeling away layers of an entire onion (complex software) versus just cutting through the entire onion and only using a section of it. The fact that I was able to start off as a Junior working on the full stack is a huge blessing because each week I still get to touch the front and back end! I do sometimes feel the urge to deep dive and specialize in one thing though, which is something I'll think about down the road!

Specifically regarding jumping around, my belief is that it's better to focus on fundamentals right now and to be careful about how many new things I dedicate learning time to. It a balance I'm always working on, but essentially I try to be cognizant of an irrational FOMO in favor of learning one thing well. To circle back around, that's why I deliberately chose to try and take as many front end tickets as possible my first year, rather than bouncing back and forth at random. Hope this helps!
