### ISSUE TITLE
tips, advices for figure skating learners

### ISSUE THREAD

**Issue by ArekSliwa** [AimeeKnight/ama#13]
Hi Aimee!
I'm so inspired by your story and I see similarities to my "life story". I was studying dramatic acting in Poland and switched to learning programming, beginning with HTML, CSS and falling in love with the JavaScript world and it's possibilities. My passion is still growing day by day. Actually, I'm learning Angular 2 now and a better job is just around the corner :) But... I see how important it is to save the body/mind harmony. My favourite classes during the studying were dance and other movement classes. I always liked watching figure skaters and this winter I decided to combine my dancing skills with ice skating challenges. I'm learning very fast but I need some exercises, tips and advice for learning further, especially how to learn single jumps :) Do you have any interesting materials or maybe your own videos while learning?

**Comment by AimeeKnight** [comment]
Hi @ArekSliwa! 

This might be one of the most fun questions I've received! It's also been a good bit of time since I coached! The two most important pieces of practical advice I have for people learning to skate who aren't itty bitty toddlers is to stay low in your knees and to fall forward. The older you get, the more upright and less limber you get, so it's important to make sure when you fall, you're as low to the ice as possible and that you fall forward towards your hands. Falling back and hitting your head on the ice isn't very fun. As far as learning single jumps, if you learn like most people by doing things see if you can get access to a jumping harness, or just practice the jumps off the ice first (even with your skates on). Finally, I definitely think for some people who may be visual learners, it helps to actually watch other people skate! Hope that helps, and good luck!

**Comment by ArekSliwa** [comment]
Thanks for quick answer! I like to be funny ;)  So I will buy a helmet before jumping. I don't want to hit my head on the ice because this is where my JavaScript skills exists..  :)

**Comment by AimeeKnight** [comment]
Ha! Yep! That's what I was thinking!
