### ISSUE TITLE
Multi developer workflow, same project

### ISSUE THREAD

**Issue by mharding7va** [AimeeKnight/ama#14]
How does the companies you have worked with handle multiple developer working on the same project and managing source with Git?  

We are using CodeAnywhere and ShiftEdit which handles the process  nicely, but doesn't work for offline development.

**Comment by AimeeKnight** [comment]
Hi @mharding7va. With Git, the companies I've worked for used both public and private repos. We'd typically have one master branch and we'd created feature branches off of that. I'd say one thing that helps when working on a larger team is breaking your stories up and shipping often so you don't end up with large merge conflicts from long running feature branches. I've also started using http://gitup.co/ to make rebasing and reviewing commits a little nicer. Of course, you can develop offline, but you'd need to be online in order to push your changes to the remote. Hopefully that helps and I understand your question. Let me know if not! :smiley:
