### ISSUE TITLE
Angular vs React

### ISSUE THREAD

**Issue by aaronendsley** [AimeeKnight/ama#16]
Hello,

I was wondering which framework is better for beginners who understand the basics of JS and have written their own apps in JavaScript, Angular or React?

**Comment by AimeeKnight** [comment]
@VeritasX Tough question! Personally I think it depends on a bunch of things. Here's a list of things worth considering (in order of importance) IMO.
1. Which tool do I think will help me grow as a developer? For me the answer was definitely React since I'm able to learn more functional concepts and more vanilla JavaScript.
2. What am I excited about? (Because I'll be more likely to stick with it and not jump around.) Totally up to you!
3. Is a quick MVP important? Angular is probably a better bet here.
4. Will I be looking for work soon? If so, do companies I'm interested in prefer knowledge of one over the other? Personally I think this is a little silly since a good developer will be able to pick up a new tool quickly! 

Hope this helps! Let me know if you have other questions!

**Comment by mattmccullar** [comment]
I would like to add to this... Coming from Rails, Ember is very attractive to me, and the devs have been incredibly passionate. With React really pushing forward and innovating, everything seems to be following it or branching off to something similar. Angular, on the other hand, I don't see 2 being common, and 1 is already far behind. **Does Ember have a place in this 'day and age' of Javascript?**

Question 2: have you hear of Elm? http://elm-lang.org/ -- What is your thoughts for the future of Elm and the Web? I have been learning it in my free time and it's highly enjoyable and interesting.

Finally, thoughts on Phoenix/Elixir? Elixir seems to be, like Elm, rapidly gaining popularity from the ruby crowd, as well as the functional programming crowd.

**Comment by AimeeKnight** [comment]
Hi @mmccullar! Is this question in regards to introducing this on a team, or for you personally?

**Comment by mattmccullar** [comment]
Thanks for the fast response! This is for me personally.

**Comment by AimeeKnight** [comment]
@mmccullar, I definitely don't think there's a right or wrong answer so here's the advice I personally follow ATM. So far I've used Ruby and JavaScript. Since those languages are somewhat similar, I thought it was important for me to start to explore other paradigms. With that said, since I spent my day to day in Angular last year, I decided to learn React since it was very different. I haven't looked at Elixir yet, but I am currently looking at Elm for the same reason... It's very different from anything I've used before. 

All that to say, I'd chose a technology to explore in my free time based on what I'm least familiar with. If I had only done Elm, I'd probably look at Angular 1 and Ember! 😉 There are still a lot of production code bases (and companies making a profit) using technologies that are a few years old so they're still worth learning IMO. Hope this helps!

**Comment by mattmccullar** [comment]
Definitely, thank you for the perspective! I spent 3-4 months doing nothing but Angular hardcore, 70-90 hours a week - I am pretty sick of it to be honest. Elm is so refreshing in comparison!

Thanks for your perspective! =)

P.S: You are one of my top 3 favorite hosts on devchat.tv - Love to hear your perspective on things. Sometimes hearing people with 10+ years in the industry talk about things is not very easy to relate to.

**Comment by AimeeKnight** [comment]
@mmccullar 😀 I can understand for sure! I really appreciate it. Thank you!
