### ISSUE TITLE
Beginner Coder Advice

### ISSUE THREAD

**Issue by tonymorristm** [AimeeKnight/ama#2]
What path would you suggest for a beginning coder to take? 
Javascript or
Ruby/Rails

I am about 1/2 thru Free Code Camp and as you probably know, Quincy is a proponent for Javascript.
I also read Josh Kemp's blog and he is a proponent for Ruby/Rails.

**Comment by tonymorristm** [comment]
What path would you suggest for a beginning coder to take? 
Javascript or
Ruby/Rails

I am about 1/2 thru Free Code Camp and as you probably know, Quincy is a proponent for Javascript.
I also read Josh Kemp's blog and he is a proponent for Ruby/Rails.

**Comment by AimeeKnight** [comment]
Hi @tonymorristm! I tend to say 'it depends' for a lot of questions, and this is one of those times. :) With JavaScript, you'll definitely get to 'Hello World', much faster, but once you move past the basics of DOM manipulation/jQuery, things can get a little tricky when you're new to programming. That's why Ruby/Rails can be awesome for beginners. The only big challenge with Ruby/Rails for a beginner is getting your environment set up. 

My advice would probably match the approach I took. When you totally new, spend a little time building some things with jQuery/JavaScript. Once you hit object oriented topics, switch to Ruby/Rails. (If there's a Rails Bridge in your area, see if you can attend with a girl you might know. They have an install fest night where people can help you get a Ruby/Rails environment set up!) I'd then spend a good bit of time with Ruby/Rails, making sure you have a solid grasp of OOP. Finally, once you have that down, you can move back to JavaScript and start tackling new challenges like asynchronous programing!

Hope that helps. Let me know if you have other questions!
