### ISSUE TITLE
Hi, you think is important to learn Elm now a days?

### ISSUE THREAD

**Issue by Rolando-Barbella** [AimeeKnight/ama#21]

**Comment by AimeeKnight** [comment]
Hi @Rolando-Barbella I'm so sorry for the delay! 

The length of time that you've been programming will greatly influence my answer! If you're new, I would not recommend picking up Elm first, simply because there aren't a lot of opportunities out there for newer devs to work with it. If you have been programming for awhile, and are looking to pick up a second or third language I think learning Elm is an excellent idea. Personally, I feel that there's a lot of room for growth as a developer when you start exploring a vastly different paradigm. Hope this helps!

**Comment by Rolando-Barbella** [comment]
Hi Aimee, no worries about the delay and thanks for the answer, I have been coding for a bit more than 2 years, is true that Elm won't get you a lot a money now, I'm in the process of deciding between picking a new language or becoming a full stack Js developer, wanted to find out others opinions first :)
