### ISSUE TITLE
Getting better with CSS

### ISSUE THREAD

**Issue by CBedzz** [AimeeKnight/ama#22]
Aimee, first off, thank you so much for all your contributions helping new (and old) programmers like myself learn and mature as a coder.

My question is regarding css.  I've been spending so much time trying to learn React and javascript, that my CSS skills have been neglected.  I seem to do just enough  to get it to work while I have focused on the JS portion of my SPAs.  Any hints/tips/advice/resources on learning and advancing my CSS chops?

Thanks!

**Comment by AimeeKnight** [comment]
Hi @CBedzz! 

I just added a new post to my blog here: http://www.aimeemarieknight.com/It's-Not-Dark-Magic-Pulling-Back-the-Curtains-From-Your-Stylesheets/ that may be a good place to start. For me, it was a matter of flipping my mindset so that I took the same approach to getting better with JavaScript as I did with CSS. I needed to prioritize it, and also go about it systematically. That just meant taking time to read the documentation rather than guessing why something wasn’t working the way it should.

Here are some other great resources I’ve used: https://gist.github.com/AimeeKnight/77b36738ec876965c6db5c6d39f4ef4f

Hope this helps, and feel free to reach out with any other questions!
