### ISSUE TITLE
Question about React best practices

### ISSUE THREAD

**Issue by Jcroxford** [AimeeKnight/ama#23]
Hey @AimeeKnight! 

I have a question for you about React. I listened to the [Learning React.js](http://thewebplatformpodcast.com/86-learning-reactjs) podcast you were in last year and a lot of the discussion you guys had (at least in the middle of the podcast) revolved around breaking down monolithic components into more composable components. 

Right now I feel like I have a pretty solid grasp on how to build apps using React, but my components are pretty much still monolithic. xD I'm trying to figure out the best way to organize my code but other than the page in React's docs [Thinking In React](https://facebook.github.io/react/docs/thinking-in-react.html) I haven't been able to find any solid examples of how I should really be breaking things down and structuring my app. Do you have or know of any good practical examples I can review to further my understanding?

**Comment by AimeeKnight** [comment]
Hey there @Jcroxford! I would highly recommend Cory House's [Creating Reusable React Components](https://www.pluralsight.com/courses/react-creating-reusable-components) on Plurlsight. We also had him on JavaScript Jabber a few weeks ago to discuss the course so that may be a great starting point! You can have a listen [here](https://devchat.tv/js-jabber/jsj-269-reusable-react-javascript-components-cory-house). Let me know if this helps!

**Comment by Jcroxford** [comment]
Wow thanks for the resources! Listened to the podcast last night and I'm checking out the course right now. This is pretty much exactly what I was looking for. Thanks so much @AimeeKnight! :)

**Comment by AimeeKnight** [comment]
You're welcome @Jcroxford! Happy to help! 😃
