### ISSUE TITLE
Why the switch from Ruby to Javascript?

### ISSUE THREAD

**Issue by treble37** [AimeeKnight/ama#5]
Hi Amy,

I really enjoy listening to your stories on the JS Jabber.  I recall hearing you mention that you switched from Ruby to Javascript, and if you don't mind, I was curious - what made you make the switch?  Better potential opportunities?  A keener interest in the front end?

**Comment by AimeeKnight** [comment]
Thank you! :smiley:

That's a really good question, and it was actually a tough choice! One factor in my decision was probably the bootcamp I attended, the Nashville Software School. The curriculum at the time that I was there was divided into three months of JavaScript (including Node), and three months of Ruby/Rails. With so many programs focusing almost entirely on Ruby at the time, I thought it was really exciting that we were able to look at both languages equally.

When it came down to the decision, I went the JavaScript route because I felt it would be more challenging. Learning to use an asynchronous language has been exactly that, and I'm glad I went that route! On top of that, I love that Node is more low level than Rails, because I feel like I'm able to learn more that way. I also really wanted to be a full stack developer, and be able to use a front end framework along with Node on the back end!
